### Creates a new patient entity
POST http://lb-c43d55fd.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John Doe",
    "email": "test@example.com",
    "address": "123 main street",
    "dateOfBirth": "1995-09-09",
    "registeredDate": "2026-02-01"
}


### Creates a new patient entity with billing account
POST http://lb-c43d55fd.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe with Billing Account",
  "email": "test_billingaccount@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2026-02-01"
}

### Creates a new patient entity with Kafka messaging
POST http://lb-c43d55fd.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Franz Kafka",
  "email": "metamorphosis_test@kafka.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2026-02-01"
}

